### PR TITLE
Refactor .drone.yml

### PR DESCRIPTION
**Pull request by assafmo**
Matching PRs:
https://github.com/enigmampc/enigma-core/pull/279
https://github.com/enigmampc/enigma-contract/pull/198

- Until we have a good enough testing framework: Test that a new worker joins the network and syncs correctly. (Cc: @lenak25)
- Add a cleanup step to the CI.
- Small refactoring.

### CODE REVIEW

**Comment by assafmo** [comment]
@lenak25 Ready for your review 🦄

**Comment by lacabra** [comment]
@assafmo I warn about modifying `.drone.yml` "unilaterally" in one repo only. Right now, the drone files in the three main repos are all analogous and very similar, so that they are easy to maintain. @reuvenpo and I led the work on these files that got us to where we are. I would ask a review from either or both of us before merging this, when you feel this is ready.

**Review by lenak25 — DISMISSED** [review]
Great!

**Comment by lacabra** [comment]
@assafmo In the latest build, all the integration tests pass, the 4th worker inits successfully, see [this link](https://drone.enigma.co/enigmampc/enigma-p2p/600/1/2), L12338: 
```
worker_4     | 2020-01-23T19:57:40Z INFO [P2P-MainController] - success InitWorkerAction
```
but there is never a `success syncing pipeline` message, so the build times out and errors out.

**Review by lacabra — APPROVED** [review]

**Pull request merged**
