### PR TITLE
BUG: fix web3 -> web3Utils in crypto utils

### PR DESCRIPTION
**Pull request by lacabra**
When only using Web3 utilities, use instead `web3-utils` where we don't need to initialize a provider.

Otherwise, I'm getting an error like the one below when starting the P2P:
```
p2p-proxy_1   | /root/enigma-p2p/node_modules/web3-providers/dist/web3-providers.cjs.js:49
p2p-proxy_1   |       if (provider.sendPayload && provider.subscribe) {
p2p-proxy_1   |                    ^
p2p-proxy_1   | 
p2p-proxy_1   | TypeError: Cannot read property 'sendPayload' of undefined
p2p-proxy_1   |     at ProviderResolver.resolve (/root/enigma-p2p/node_modules/web3-providers/dist/web3-providers.cjs.js:49:20)
p2p-proxy_1   |     at Web3.AbstractWeb3Module (/root/enigma-p2p/node_modules/web3-core/dist/web3-core.cjs.js:24:51)
p2p-proxy_1   |     at new Web3 (/root/enigma-p2p/node_modules/web3/dist/web3.cjs.js:30:68)
p2p-proxy_1   |     at Object.<anonymous> (/root/enigma-p2p/src/common/cryptography.js:2:14)
p2p-proxy_1   |     at Module._compile (internal/modules/cjs/loader.js:805:30)
p2p-proxy_1   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
p2p-proxy_1   |     at Module.load (internal/modules/cjs/loader.js:672:32)
p2p-proxy_1   |     at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
p2p-proxy_1   |     at Function.Module._load (internal/modules/cjs/loader.js:604:3)
p2p-proxy_1   |     at Module.require (internal/modules/cjs/loader.js:711:19)
p2p-proxy_1   |     at require (internal/modules/cjs/helpers.js:14:16)
p2p-proxy_1   |     at Object.<anonymous> (/root/enigma-p2p/src/worker/state_sync/receiver/StateSyncReqVerifier.js:1:16)
p2p-proxy_1   |     at Module._compile (internal/modules/cjs/loader.js:805:30)
p2p-proxy_1   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
p2p-proxy_1   |     at Module.load (internal/modules/cjs/loader.js:672:32)
p2p-proxy_1   |     at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
```

### CODE REVIEW

**Comment by lenak25** [comment]
Do you know why this change fixed the error? The `web3.utils` is being used in many places in the code and tests, like [here](https://github.com/enigmampc/enigma-p2p/blob/master/test/ethereum/basic_eth_test.js)

**Comment by lacabra** [comment]
Not entirely sure. My hypothesis is that a new release of `web3.js` (latest as of a few days ago: https://www.npmjs.com/package/web3) makes this check more strict where it wasn't before. But I don't get why I see it in some builds and not on the CI of the P2P. Going through the various instances where this might be an issue. In the link you paste above, there are two different instances, one in which web3 is instantiated from scratch (where this would be a problem), one where it gets instantiated from api.w3() where it has been intialized properly.

PS: the force-push above is to correct a previous unsigned commit which is now signed.

**Comment by lacabra** [comment]
@lenak25: to your point, more errors started appearing now anywhere in the tests where this was used. Corrected those in 8c0692c and cd7cbab.

This should be ready to merge now.

**Comment by lacabra** [comment]
Now the build cd7cbab fails because of truffle... this makes no sense.

**Comment by lacabra** [comment]
Had to lock web3 to `1.0.0-beta.37` to get unit tests to pass. Now the build succeeds.
I suggest we tackle the upgrade of web3 on a separate issue (low priority for now).

**Pull request merged**
